version: "3"
services:
    app:
        image: ghcr.io/ltlapy/docker-lapis:amd64
        container_name: app
        restart: unless-stopped
        env_file: .env
        working_dir: /app
        command: lapis server
        volumes:
            - ./src:/app
            - ./logs:/var/log/openresty/
            - openresty_tmp:/tmp/openresty
        ports:
            - 9090:8080

volumes:
    openresty_tmp:
    # openresty_logs: