version: "3"
services:
    app:
        image: lapis:1.12.0-1
        container_name: app
        restart: unless-stopped
        env_file: .env
        working_dir: /app
        build:
            # build the image from Dockerfile
            context: .
        volumes:
            - ./src:/app
            - ./logs:/var/log/openresty/
            - openresty_tmp:/tmp/openresty
        #command: lapis server
        ports:
            - 9090:8080

volumes:
    openresty_tmp:
    # openresty_logs: